#%RAML 1.0
title: healthcare-ehr2sfhc-sync-process-api
baseUri: http://healthcare-ehr2sfhc-sync-process-api.cloudhub.io/api
version: v1


/patients/{patientId}/migrateClinicalData:
  displayName: migrateClinicalData
  post:
    description: Migrate clinical data from EHR to CRM
    responses:
      202:
        body:
          application/json:
            example: |
              {"message": "The migration process has started and will be completed asynchronously."}